# -*- coding: utf-8 -*-
# """
# /***************************************************************************
#  Therm Tools
#                                  A QGIS plugin
#  This window has access to Tools for Therm application.
#  Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
#                              -------------------
#         begin                : 2022-08-25
#         git sha              : $Format:%H$
#         copyright            : (C) 2022 by SenseHawk
#         email                : kiranh@sensehawk.com
#  ***************************************************************************/
#
# /***************************************************************************
#  *                                                                         *
#  *   This program is free software; you can redistribute it and/or modify  *
#  *   it under the terms of the GNU General Public License as published by  *
#  *   the Free Software Foundation; either version 2 of the License, or     *
#  *   (at your option) any later version.                                   *
#  *                                                                         *
#  ***************************************************************************/
# """

from qgis.PyQt.QtCore import Qt, QCoreApplication
from qgis.PyQt import QtWidgets, uic
from qgis.core import Qgis
from time import time
from ..windows.autoNumbering_utils import *

import os
import numpy as np


class ThermNumberingWidget(QtWidgets.QWidget):

    def __init__(self, thermToolobj, iface):
        """Constructor."""
        super(ThermNumberingWidget, self).__init__()
        uic.loadUi(os.path.join(os.path.dirname(__file__), 'AutoNumbering.ui'), self)
        self.canvas_logger = thermToolobj.canvas_logger
        self.logger = thermToolobj.logger
        self.thermToolobj = thermToolobj
        self.projectuid = thermToolobj.project_details['uid']
        self.iface = iface
        self.canvas =self.iface.mapCanvas()
        self.approve.clicked.connect(self.string_numbering)
 


    def stringNumber_configuration(self):
        canvas  = self.canvas
        rotation = canvas.rotation()
        Angle = 0
        if rotation < 0:Angle = abs(rotation)
        elif rotation == 0:Angle = abs(rotation)
        else:Angle = -abs(rotation)

        return self.Width.value(), self.Height.value(),Angle,self.Prefix.text(),self.Suffix.text()


    def string_numbering(self):
        startTime = time()
        Vlayer = self.iface.activeLayer()
        Vlayer.startEditing()
        Vfeatures = Vlayer.getFeatures()
        module_width, module_height, angle, Prefix, Suffix = self.stringNumber_configuration()
        featureslist = [feature for feature in Vfeatures] #QgsfeatureIterator[] => Qgsfeatures
        featuresobjlist = [Table(feature) for feature in featureslist] 
        sorted_tables = sorted(featuresobjlist, key=lambda x: x.raw_lonlat_y, reverse=True)
        Topmost_table = topmost_table(sorted_tables)
        anchor_point = max(Topmost_table.raw_utm_coords, key=lambda x: x[1])
        # Adding rotated utm_coords as a attribute to featureObj
        update_rotated_coords(featuresobjlist, anchor_point, angle) 
         #Adding Table_row and Table_column numbers to tableObj
        table_numbering(featuresobjlist, Vlayer)
        #Grouping issues falling in Parent table and updating Parent Trow and Tcolumn number to issuesObj 
        update_issue_tRow_tColumn(featuresobjlist, Vlayer) 
        # Updating row and column to issuesObj 
        update_issue_Row_column(self.projectuid , featuresobjlist, Vlayer, module_height, module_width, angle) 
            
        Vlayer.startEditing()
        """String NUmbering"""
        if self.stringnum_type.currentText() == 'Basic' or self.stringnum_type.currentText() == 'Basic+module':
            for featureobj in featuresobjlist:
                if featureobj.feature['class_name'] != 'table':
                    Trow = featureobj.feature['table_row']
                    Tcolumn = featureobj.feature['table_column']
                    Irow = featureobj.feature['row']
                    Icolumn = featureobj.feature['column']
                    if self.stringnum_type.currentText() == 'Basic':
                        basic_number = f"{Prefix}-R{Trow}-T{Tcolumn}-{Suffix}"
                        try:
                            featureobj.feature['string_number'] = basic_number.strip('-')
                        except KeyError:
                            self.canvas_logger("String number field does not exist!", level=Qgis.Warning)
                        Vlayer.updateFeature(featureobj.feature)
                    elif self.stringnum_type.currentText() == 'Basic+module':
                        basicModule_number = f"{Prefix}-R{Trow}-T{Tcolumn}-R{Irow}-C{Icolumn}-{Suffix}"
                        featureobj.feature['string_number'] = basicModule_number.strip('-')
                        Vlayer.updateFeature(featureobj.feature)
                    
        elif self.stringnum_type.currentText() == 'Existing+module':
            for featureobj in featuresobjlist:
                if featureobj.feature['class_name'] == 'table' and featureobj.issue_obj :
                    if not featureobj.feature['string_number']:
                        Existing_SN = "Existing string number does not exist"
                    else:
                        Existing_SN = featureobj.feature['string_number']
                    for issue_obj in featureobj.issue_obj:
                        Irow = issue_obj.feature['row']
                        Icolumn = issue_obj.feature['column']
                        basicModule_number = f"{Prefix}-{Existing_SN}-R{Irow}-C{Icolumn}-{Suffix}"
                        print(basicModule_number)
                        issue_obj.feature['string_number'] = basicModule_number.strip('-')
                        Vlayer.updateFeature(issue_obj.feature)

        endTime = time()
        duration = int(round((endTime - startTime) * 1000))
        Vlayer.commitChanges()
        self.canvas_logger(f'<b>String_numbeirng</b> done in {duration}ms.', level=Qgis.Success)