# -*- coding: utf-8 -*-
# """
# /***************************************************************************
#  Terra Tools
#                                  A QGIS plugin
#  This window has access to Tools for Terra/SCM application.
#  Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
#                              -------------------
#         begin                : 2022-08-25
#         git sha              : $Format:%H$
#         copyright            : (C) 2022 by SenseHawk
#         email                : kiranh@sensehawk.com
#  ***************************************************************************/
#
# /***************************************************************************
#  *                                                                         *
#  *   This program is free software; you can redistribute it and/or modify  *
#  *   it under the terms of the GNU General Public License as published by  *
#  *   the Free Software Foundation; either version 2 of the License, or     *
#  *   (at your option) any later version.                                   *
#  *                                                                         *
#  ***************************************************************************/
# """

from ..sensehawk_apis.core_apis import save_project_geojson, get_project_geojson
from ..sensehawk_apis.scm_apis import get_models_list, detect
from ..tasks import clipRequest, detectionTask, approveTask

from qgis.PyQt import QtWidgets, uic
from qgis.core import QgsMessageLog, Qgis, QgsApplication, QgsTask, QgsFeatureRequest, QgsPoint
from qgis.PyQt.QtCore import Qt
import os
import qgis
from PyQt5.QtGui import QKeySequence

from .ml_service_map import MLServiceMapWidget

from PyQt5.QtWidgets import QApplication

import json

class TerraToolsWidget(QtWidgets.QWidget):

    def __init__(self, project):
        """Constructor."""
        super(TerraToolsWidget, self).__init__()
        uic.loadUi(os.path.join(os.path.dirname(__file__), 'terra_tools.ui'), self)
        self.project = project
        self.parent = self.project.project_tab
        self.loadModelsButton.clicked.connect(self.load_models)
        self.detectButton.clicked.connect(self.start_detect_task)
        self.approveButton.clicked.connect(self.start_approve_task)
        self.clipButton.clicked.connect(self.start_clip_task)
        self.requestModelButton.clicked.connect(self.request_model)
        self.core_token = self.project.core_token
        self.project_details = self.project.project_details
        self.class_maps = self.project.class_maps
        self.class_groups = self.project.class_groups
        self.iface = self.project.iface
        self.active_layer = self.project.vlayer
        self.models_dict = {}
        # ML Service Map
        self.ml_service_map_widget = None

    def uncheck_all_buttons(self):
        for button in self.findChildren(QtWidgets.QPushButton):
            if button.isCheckable():
                button.setChecked(False)

    def logger(self, message, level=Qgis.Info):
        QgsMessageLog.logMessage(message, 'SenseHawk QC', level=level)

    def request_model(self):
        if not self.ml_service_map_widget:
            self.ml_service_map_widget = MLServiceMapWidget(self.project)
        if self.project.active_tool_widget != self.ml_service_map_widget:
            self.project.active_tool_widget.hide()
            self.project.project_tab_layout.replaceWidget(self.project.active_tool_widget, self.ml_service_map_widget)
            self.project.active_tool_widget = self.ml_service_map_widget
        self.ml_service_map_widget.show()
        self.uncheck_all_buttons()
        self.requestModelButton.setChecked(True)

    def load_models(self):
        # Get list of available models
        self.models_dict = get_models_list(self.project_details["uid"], self.core_token)
        models_list = list(self.models_dict.keys())
        if models_list:
            list_items = models_list
        else:
            list_items = ["No models available"]
        # Clear list to avoid duplicates
        self.detectionModel.clear()
        self.detectionModel.addItems(list_items)

    def start_clip_task(self):
        def callback(task, logger):
            result = task.returned_values
            if result:
                logger(str(result["message"]))
        self.logger("Clip task starting...")
        clip_task_inputs = self.logger, self.project_details, self.load_window.geojson_path, self.class_maps, self.core_token
        clip_task = QgsTask.fromFunction("Clip Request", clipRequest, clip_task_input=clip_task_inputs)
        clip_task.statusChanged.connect(lambda:callback(clip_task, self.logger))
        QgsApplication.taskManager().addTask(clip_task)

    def start_detect_task(self):
        def callback(task, logger):
            result = task.returned_values
            if result:
                logger(str(result))
        self.logger("Detection called..")
        geojson = get_project_geojson(self.project_details.get("uid", None), self.core_token, "terra")
        self.logger("Getting model information...")
        model_name = self.detectionModel.currentText()
        if model_name not in self.models_dict:
            self.logger("Invalid model...")
            return None
        model_url = self.models_dict[model_name]
        model_details = [model_name, model_url]
        self.logger("Initiating detection request task...")
        detection_task = QgsTask.fromFunction("Detect", detectionTask,
                                              detection_task_input=[self.project_details, geojson,
                                                                    model_details, self.project.project_tabs_widget.load_window.home.user_email,
                                                                    self.core_token])
        detection_task.statusChanged.connect(lambda:callback(detection_task, self.logger))
        QgsApplication.taskManager().addTask(detection_task)

    def start_approve_task(self):
        def callback(task, logger):
            result = task.returned_values
            if result:
                logger(str(result))
        self.logger("Approve called...")
        geojson = get_project_geojson(self.project_details.get("uid", None), self.core_token, "terra")
        approve_task = QgsTask.fromFunction("Approve", approveTask,
                                            approve_task_input=[self.project_details, geojson,
                                                                self.project.project_tabs_widget.load_window.home.user_email,
                                                                self.core_token])
        approve_task.statusChanged.connect(lambda:callback(approve_task, self.logger))
        QgsApplication.taskManager().addTask(approve_task)
