# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SensehawkQC
                                 A QGIS plugin
 This plugin will load and save SenseHawk projects needing quality check.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-08-25
        copyright            : (C) 2022 by SenseHawk
        email                : kiranh@sensehawk.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SensehawkQC class from file SensehawkQC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sensehawk_qc import SensehawkQC
    return SensehawkQC(iface)
