# Production env
CORE_URL = "https://core-server.sensehawk.com"
MAP_SERVER_URL = "https://mapserver.sensehawk.com/"
V2_MAP_SERVER_UTL = "https://maps-server.sensehawk.com/"
TERRA_URL = "https://terra-server.sensehawk.com"
THERM_URL = "https://therm-server.sensehawk.com"
SCM_TRAIN_URL = "https://scm-train.sensehawk.com"
SCM_INFERENCE_URL = "https://scm-inference.sensehawk.com"
SID_URL = "https://sid.sensehawk.com/detect-solar-issues"
CLIP_FUNCTION_URL = "https://clip-raster-server.sensehawk.com"
THERMAL_TAGGING_URL = "https://sid-tagging-server.sensehawk.com" 
API_SENSEHAWK = "https://api.sensehawk.com"
S3_REGION="ap-south-1"
S3_BUCKET="sh-inc-ap-south-1"
NEXTRACKER_URL = "https://nextracker-server.sensehawk.com"

# MLSense
SCMAPP_URL = "http://mlsense.sensehawk.com:8080" 
API_NEW_SENSEHAWK = "https://api.sensehawk.com"

# # Staging env
# CORE_URL = "https://core-stage-server.sensehawk.com"
# MAP_SERVER_URL = "https://mapserver.sensehawk.com/"
# TERRA_URL = "https://terra-stage-server.sensehawk.com"
# THERM_URL = "https://therm-stage-server.sensehawk.com"
# SCM_TRAIN_URL = "https://scm-train-stage.sensehawk.com"
# SCM_INFERENCE_URL = "https://scm-inference-stage.sensehawk.com"
# CLIP_FUNCTION_URL = "https://848rwfqtw0.execute-api.us-west-2.amazonaws.com/default/clipRaster"
# SID_URL = "https://sid-stage.sensehawk.com/detect-solar-issues"
# API_SENSEHAWK = "https://api-new.sensehawk.com"
# THERMAL_TAGGING_URL = "https://thermal-tagging-test-server.sensehawk.com"
# S3_REGION="ap-south-1"
# S3_BUCKET="sh-inc-ap-south-1"
# NEXTRACKER_URL = "https://nextracker-test-server.sensehawk.com"