# This is single spurce of truth for one project used for inference
# This is expected to found in QGIS configuration

# global
project_uid: "VzZHZIwo1K" #TODO:

# user specific
email: "ssolanki@sensehawk" #TODO:

# dataset and project specific
ortho_url: "< https://sensehawk-test-data-management.s3.amazonaws.com/core/VzZHZIwo1K/ml_models.zip >" # TODO:
geo_json:

# Inference Specific Config
inference:
  models_zip_url: "" # TODO:
  detection:
    conf_score: 0.5
    iou_score: 0.6
    run_id: ""
    filter_components_by_dimension_in_meter:
      module:
        width: 1.9
        height: 1.1
        width_diff: 40
        height_diff: 40
        area_diff: 2000

      pole:
        width: 0.8
        height: 0.8
        width_diff: 40
        height_diff: 40
        area_diff: 2000

      pallet:
        width: 2.6
        height: 1.37
        width_diff: 40
        height_diff: 40
        area_diff: 2000

  segmentation:
    conf_score: 0.5
    run_id: ""

  keypoint:
    conf_score: 0.5
    run_id: ""
